---
ID: "fba46713-f5a3-4e40-b23d-3cd163edcd9b"
Parent: "35b978b9-1fce-450a-842d-0d53ee1c5428"
Template: "81afaa32-f1b0-47de-a8e6-3e443a06510e"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/RobStorefront/Currency Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "f8abfa72-0fba-44a5-9122-cf11acb0ea61"
  Hint: Currency Set
  Value: "{0F65742E-317F-44B0-A4DE-EBF06209E8EE}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D5BD9BB5-FCC1-4ACC-9E7C-6D42F6848DFB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Currency Configuration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190916T032947Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "34618c5d-ef13-4b8c-9730-ccf2d344dce4"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T032947Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
