---
ID: "1f912375-47fc-405e-9f7a-b124fb44a3c6"
Parent: "35b978b9-1fce-450a-842d-0d53ee1c5428"
Template: "8753e14e-8ce5-4be3-8e63-486c7ee87702"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/RobStorefront/Email Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "c3c59a8c-a79f-43ec-b332-cdbef8e4d19e"
  Hint: From Email Address
  Value: info@sitecore.net
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{7D40F452-6F70-43BB-BC23-A72F2C34B902}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Email Configuration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190916T032947Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8400d46b-25d7-427b-8da6-7e6a3838f579"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T032947Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
