---
ID: "ebcb1c01-1894-4f73-b398-afc5db5ac164"
Parent: "021c37cb-6a18-4063-bf84-fcfb04191fc6"
Template: "205f3ef7-05bb-452d-a338-1d0bb334267c"
Path: /sitecore/content/RobCommerce/RobStorefront/Settings/Commerce/Catalog Configuration
DB: master
SharedFields:
- ID: "55bcda17-f08b-40e7-b112-9945db903303"
  Hint: Catalog
  Value: "{59DDADC1-9B88-727E-9E14-3F6CF321AE0F}"
- ID: "edeca58f-a268-4160-b609-e2944b3e459a"
  Hint: Start Navigation Category
  Value: "{B893C063-6238-ED57-700D-72862C56038D}"
- ID: "d8950716-21ad-43c3-8763-74d8cd77c324"
  Hint: Include subcategory products
  Value: 
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Katalogkonfiguration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190916T033128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4d5c0fcc-c4d4-42bb-9de0-b806368fbc65"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T033128Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Katalogkonfiguration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190916T033144Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "63fc7d89-c1a6-41e2-98df-9241404de569"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T033144Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Catalog Configuration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180524T074535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "64c06900-b996-4243-82a7-31e2c9098456"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T033222Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: カタログ設定
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190916T033159Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "33d02c3c-64fc-4289-bd03-19f3c020a8e5"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190916T033159Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
