---
ID: "0b44d688-fabc-4685-9b8b-a948d985d30b"
Parent: "a979ce46-7f5d-4bcc-bed9-6a3936a73d13"
Template: "7c549b81-2855-4dd9-ab20-4ab553db70ce"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/RobStorefront/Account Management Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{6E3A9836-FC8C-481C-8642-E08AFB975DE0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Account Management Configuration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T022808Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c228e0f0-d4e9-44c1-8e1f-fa3e02feda2d"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190905T022808Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
