---
ID: "fb941458-3da4-46c3-adba-a6994e5e23f7"
Parent: "a979ce46-7f5d-4bcc-bed9-6a3936a73d13"
Template: "d36bae09-f787-4b31-bada-d830e0799257"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/RobStorefront/Catalog Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "d7cad4b2-7027-4d9b-a813-747105fd50c8"
  Hint: Catalog
  Value: "{59DDADC1-9B88-727E-9E14-3F6CF321AE0F}"
- ID: "00a621a0-d2d1-4cf0-831f-36da2e8d2a91"
  Hint: Start Navigation Category
  Value: "{B893C063-6238-ED57-700D-72862C56038D}"
- ID: "fdd0d6ae-bccd-4cd9-a078-3103d720d2e7"
  Hint: Use Direct Navigation
  Value: 1
- ID: "453f14e4-1045-4e50-be74-dd0a89ee764a"
  Hint: ExcludeCategoriesFromSearchResults
  Value: 1
- ID: "fc9c3c29-7a69-4088-8c89-22fb3d493a9a"
  Hint: GiftCardProductId
  Value: 6042986
- ID: "48420f58-f1df-4b80-8386-b62aa84e9b57"
  Hint: Gift Card Page Link
  Value: |
    <link text="" anchor="" linktype="internal" class="" title="" target="" querystring="" id="{18348778-F01A-4474-83C9-EB8112C8E072}" />
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{50E69E44-1425-4502-9589-4031F47DCD4F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
      Hint: __Display name
      Value: Catalog Configuration
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T022808Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30b1f03d-c74a-4bd2-8680-543474e8f9ed"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190905T023213Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
