---
ID: "fda24acf-c254-4696-b3f2-525240ae423d"
Parent: "9c9de238-8f42-41be-ab14-ac1d67747499"
Template: "205f3ef7-05bb-452d-a338-1d0bb334267c"
Path: /sitecore/content/RobCommerce/RobStorefront/Settings/Commerce/Catalog Configuration
DB: master
SharedFields:
- ID: "55bcda17-f08b-40e7-b112-9945db903303"
  Hint: Catalog
  Value: "{59DDADC1-9B88-727E-9E14-3F6CF321AE0F}"
- ID: "d8950716-21ad-43c3-8763-74d8cd77c324"
  Hint: Include subcategory products
  Type: Checkbox
  Value: 0
- ID: "edeca58f-a268-4160-b609-e2944b3e459a"
  Hint: Start Navigation Category
  Value: "{B893C063-6238-ED57-700D-72862C56038D}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Catalog Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180524T074535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
