---
ID: "da055616-e1f9-4fa4-934b-b9d9a2e9e2a2"
Parent: "85086856-d73c-499d-8a98-4743652ae123"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Base Themes/Commerce Components Theme/Scripts/Product Compare
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190212T042740Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
