---
ID: "fda76673-b41f-4c84-8cba-2926fed99b43"
Parent: "7b6154b6-8251-4e2d-8ab0-e8e232a6f6d7"
Template: "9c9f2f23-4195-4b23-bcd1-8e1626fcab5e"
Path: /sitecore/content/RobCommerce/RobStorefront/Home/product
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/16x16/element.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {9C9F2F23-4195-4B23-BCD1-8E1626FCAB5E}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {7755E481-E593-4624-B5E7-B516A48D4035}
    {AFC9211F-DFA8-4444-9EE0-D50A5AE76115}
    {C5D53E39-F076-4B5C-A3E5-216455C468D3}
    {811E83A6-29BA-4E49-9DC7-A6DFCA9F3209}
    {378453BF-BEEF-4F97-9E98-66CF0374B092}
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{DF080B25-1D20-4693-BFF8-E820DA40BDC5}"
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Produkt
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T215207Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ce53062e-4385-4244-8382-c2b4530a51ba"
      Hint: TwitterCardType
      Value: "{32F6A4E4-93DD-4A9C-AA60-CDEDB0BEDABB}"
    - ID: "cf7ef040-988f-40b6-a45f-813cd1f1f63b"
      Hint: Title
      Value: Product
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Produkt
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T215237Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ce53062e-4385-4244-8382-c2b4530a51ba"
      Hint: TwitterCardType
      Value: "{32F6A4E4-93DD-4A9C-AA60-CDEDB0BEDABB}"
    - ID: "cf7ef040-988f-40b6-a45f-813cd1f1f63b"
      Hint: Title
      Value: Product
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170529T101702Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "cf7ef040-988f-40b6-a45f-813cd1f1f63b"
      Hint: Title
      Value: Product
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 商品
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T215315Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ce53062e-4385-4244-8382-c2b4530a51ba"
      Hint: TwitterCardType
      Value: "{32F6A4E4-93DD-4A9C-AA60-CDEDB0BEDABB}"
    - ID: "cf7ef040-988f-40b6-a45f-813cd1f1f63b"
      Hint: Title
      Value: Product
