---
ID: "504516fc-7c10-4ea6-bab8-03fccdbfa9c6"
Parent: "8a824ffa-ff9c-4eba-b5de-8d11caefda1e"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/gulp/tasks/watchJS Copied from Storefront Branded Extension
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGd1bHBpZiBmcm9tICdndWxwLWlmJzsNCmltcG9ydCBlc2xpbnQgZnJvbSAnZ3VscC1lc2xpbnQnOw0KaW1wb3J0IGNvbG9ycyBmcm9tICdjb2xvcnMnDQovLw0KaW1wb3J0IGxvZ2luIGZyb20gJy4vbG9naW4nOw0KaW1wb3J0IGNvbmZpZyBmcm9tICcuLi9jb25maWcnOw0KaW1wb3J0IGZpbGVBY3Rpb25SZXNvbHZlciBmcm9tICcuLi91dGlsL2ZpbGVBY3Rpb25SZXNvbHZlcic7DQoNCmd1bHAudGFzaygnd2F0Y2gtanMnLCBbJ2xvZ2luJ10sICgpID0+IHsNCiAgICB2YXIgY29uZiA9IGNvbmZpZy5qczsNCiAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCkgew0KICAgICAgICBjb25zb2xlLmxvZygnV2F0Y2hpbmcgSlMgZmlsZXMgc3RhcnRlZC4uLicuZ3JlZW4pOw0KICAgIH0sIDApOw0KICAgIHJldHVybiB3YXRjaChjb25mLnBhdGgsIHsgdmVyYm9zZTogMCB9LCBmdW5jdGlvbihmaWxlKSB7DQogICAgICAgIHZhciBzdHJlYW0gPSBndWxwLnNyYyhmaWxlLnBhdGgpDQogICAgICAgICAgICAucGlwZShlc2xpbnQoKSkNCiAgICAgICAgICAgIC5waXBlKGVzbGludC5mb3JtYXQoKSkNCiAgICAgICAgICAgIC5waXBlKGVzbGludC5yZXN1bHRzKHJlc3VsdHMgPT4gew0KICAgICAgICAgICAgICAgIC8vIENhbGxlZCBvbmNlIGZvciBhbGwgRVNMaW50IHJlc3VsdHMuDQogICAgICAgICAgICAgICAgaWYgKHJlc3VsdHMuZXJyb3JDb3VudCA9PSAwIHx8IGNvbmYuZXNMaW50VXBsb2FkT25FcnJvcikgew0KICAgICAgICAgICAgICAgICAgICBmaWxlQWN0aW9uUmVzb2x2ZXIoZmlsZSk7DQogICAgICAgICAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgICAgICAgICAgY29uc29sZS5sb2coJ1BsZWFzZSBmaXggZXJyb3JzIGJlZm9yZSB1cGxvYWRpbmcgb3Igc2V0IGVzTGludFVwbG9hZE9uRXJyb3I6dHJ1ZScueWVsbG93KTsNCiAgICAgICAgICAgICAgICB9DQogICAgICAgICAgICB9KSk7DQoNCg0KICAgICAgICByZXR1cm4gc3RyZWFtOw0KICAgIH0pDQp9KTsNCg0KZ3VscC50YXNrKCdqcy13YXRjaCcsIFsnbG9naW4nXSwNCiAgICBmdW5jdGlvbigpIHsNCiAgICAgICAgZ2xvYmFsLmlzV2F0Y2hpbmcgPSB0cnVlOw0KICAgICAgICBndWxwLnJ1bignd2F0Y2gtanMnKQ0KICAgIH0p
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 1221
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/7044779B334D4C67891C03E8D30152A8.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180405T051927Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5e36735c-5915-4ddf-bef3-8bd7e141e635"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180405T051928Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
