---
ID: "d5c75fd0-a7ce-4370-bd60-00dfd7a889c0"
Parent: "b1e80643-e534-4d1f-bd43-374b3b1cbbe5"
Template: "2530e8c8-3be6-427f-8120-85caa34ec8eb"
Path: /sitecore/content/RobCommerce/RobStorefront/Presentation/Page Designs/Default
DB: master
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{C6DCF059-3804-47DA-8CCB-678EB898A22D}|{3F953BF9-0D3D-464E-B7D4-29856476127B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T215342Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
