---
ID: "aa834d5a-f45b-44b0-872f-29e30d01c0d4"
Parent: "c2b06372-d96e-410b-a6d0-897e2d79ad0e"
Template: "7c02e9f5-54b5-4ef4-bd10-f4c5d448a48c"
Path: /sitecore/content/RobCommerce/RobStorefront/Presentation/Rendering Variants/Product Bundle/Default/Bundle Groups Container/Bundle Groups Reference/Bundle Group/Bundle Group Header Container/Bundle Group Header/Product Link
DB: master
SharedFields:
- ID: "1aa68c0b-eb67-4575-9ca8-1689c2aff091"
  Hint: Tag
  Value: "{FF819CDE-E98A-4AB7-B8B0-65EE989369F7}"
- ID: "8414031e-7b85-426c-8516-84d6223a1208"
  Hint: CssClass
  Value: "product-link"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 225
- ID: "c35b2285-b4a8-406f-a91c-24a60391dc12"
  Hint: DataAttributes
  Value: href=%40%28ProductLink%29
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: Gå til produkt
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190315T063844Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: Zum Produkt gehen
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190315T064028Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: Go to product
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181214T024107Z
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "07211f80-7ffc-4df4-a4de-c8956f391850"
      Hint: Text
      Value: 商品に移動
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190315T064148Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
