---
ID: "bcdb3ebd-94b9-49cb-9cd7-b4de1fa3e182"
Parent: "e31b64ca-2e0a-47b5-8757-5b5b01408465"
Template: "e31b64ca-2e0a-47b5-8757-5b5b01408465"
Path: /sitecore/templates/Project/RobCommerce/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T214345Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
