---
ID: "999c2f01-3f1a-4710-ba43-21a231faa78c"
Parent: "b887964b-deee-4577-92e0-3bcd4882d9de"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Feature/Commerce Experience Accelerator/Product Compare/Product Compare Folder
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: wordprocessing/32x32/columns.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{A87A00B1-E6DB-45AB-8B54-636FEC3B5523}"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{3E202874-5AE3-41DE-8099-B14E2F7DA410}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180309T195001Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
