---
ID: "e5c0799e-4343-41c2-ad59-d1d1b6d758be"
Parent: "39b86c7b-cc75-401d-8b75-a3c29978e7f1"
Template: "39b86c7b-cc75-401d-8b75-a3c29978e7f1"
Path: /sitecore/templates/Feature/Commerce Experience Accelerator/Product Compare/Datasource/Product Compare/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170920T062311Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
