---
ID: "350b7fca-ee9a-41a0-864d-db0557fa7025"
Parent: "4f42c296-582c-4c0a-af87-e4439832dc90"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/sass/components/commerce/product-facet-component"
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: QGltcG9ydCAnLi4vLi4vaW5kZXgnOw0KLmN4YS1wcm9kdWN0ZmFjZXRzLWNvbXBvbmVudCB7DQogICAgcGFkZGluZzogJHBhZGRpbmcgKiAxLjI7DQogICAgbWFyZ2luLWJvdHRvbTogJG1hcmdpbjsNCiAgICBAaW5jbHVkZSBzaWRlYmFyKCk7DQogICAgLmNvbXBvbmVudC1jb250ZW50IHsNCiAgICAgICAgdWx7DQogICAgICAgICAgICBwYWRkaW5nLXRvcDogJHBhZGRpbmcvMjsNCiAgICAgICAgICAgIGxpbmUtaGVpZ2h0OjE7DQogICAgICAgICAgICBtYXJnaW4tYm90dG9tOiA0MHB4Ow0KICAgICAgICB9DQogICAgICAgIC5mYWNldC10aXRsZSB7DQogICAgICAgICAgICAmOmFmdGVyew0KICAgICAgICAgICAgICAgIGZsb2F0OnJpZ2h0Ow0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgQGluY2x1ZGUgc2lkZWJhclRpdGxlKCk7DQogICAgICAgIH0NCiAgICAgICAgdWwgew0KICAgICAgICAgICAgQGluY2x1ZGUgc2lkZWJhckxpc3QoKTsNCiAgICAgICAgfQ0KICAgIH0NCn0=
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: scss
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 500
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/9B6850E73C7B4D19B99B4CEBCBE277BB.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T100938Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "87f12cfb-9a2e-4105-934b-550eae94c41d"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180117T024250Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
