---
ID: "3d37ea75-5b3a-4eb4-a8ab-b9a3c235ed23"
Parent: "4f42c296-582c-4c0a-af87-e4439832dc90"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/sass/components/commerce/product-inventory-component"
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: QGltcG9ydCAnLi4vLi4vaW5kZXgnOw0KLmNvbXBvbmVudC5jeGEtcHJvZHVjdGludmVudG9yeS1jb21wb25lbnQgew0KICAgIGNvbG9yOiAkc2Vjb25kYXJ5LXRleHQtY29sb3I7DQogICAgYm9yZGVyOiBub25lOw0KICAgIG1hcmdpbjogOHB4IDAgMjVweCAwOw0KICAgIC5zdG9jay1pbmZvIHsNCiAgICAgICAgYm9yZGVyOiBub25lOw0KICAgICAgICBtYXJnaW4tYm90dG9tOiAwOw0KICAgIH0NCiAgICAuc3RvY2stc3RhdHVzIHsNCiAgICAgICAgJjphZnRlciB7DQogICAgICAgICAgICBjb250ZW50OiAnOic7DQogICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7DQogICAgICAgICAgICBtYXJnaW4tcmlnaHQ6IDEwcHg7DQogICAgICAgIH0NCiAgICB9DQogICAgLnN0b2NrLWNvdW50LkluLVN0b2NrIHsNCiAgICAgICAgJjpiZWZvcmUgew0KICAgICAgICAgICAgQGluY2x1ZGUgc2MtaWNvbigkc2N4YS1oYXBweWZhY2UpOw0KICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOw0KICAgICAgICAgICAgbWFyZ2luLXJpZ2h0OiAxMHB4Ow0KICAgICAgICB9DQogICAgfQ0KICAgIC5zdG9jay1jb3VudC5PdXQtb2YtU3RvY2sgew0KICAgICAgICAmOmJlZm9yZSB7DQogICAgICAgICAgICBAaW5jbHVkZSBzYy1pY29uKCRzY3hhLXNhZGZhY2UpOw0KICAgICAgICAgICAgZGlzcGxheTogaW5saW5lLWJsb2NrOw0KICAgICAgICAgICAgbWFyZ2luLXJpZ2h0OiAxMHB4Ow0KICAgICAgICB9DQogICAgfQ0KICAgIC5zdG9jay1jb3VudC1sYWJlbCwNCiAgICAuc3RvY2stY291bnQgew0KICAgICAgICBmb250LXdlaWdodDogYm9sZDsNCiAgICAgICAgY29sb3I6ICRzZWNvbmRhcnktdGV4dC1jb2xvcjsNCiAgICB9DQp9
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: scss
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 870
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/058DD217232C4439B448F61755064A54.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T100938Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "79b07a5b-4b42-4f9a-8d91-69668761235b"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180123T062013Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
