---
ID: "9690b4fb-52c5-4fd0-9d3f-7193bfbd7ffb"
Parent: "4f42c296-582c-4c0a-af87-e4439832dc90"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/sass/components/commerce/product-variant-component"
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: QGltcG9ydCAnLi4vLi4vaW5kZXgnOw0KLmN4YS1wcm9kdWN0dmFyaWFudC1jb21wb25lbnQgew0KICAgICY6YWZ0ZXIgew0KICAgICAgICBjb250ZW50OiAnJzsNCiAgICAgICAgZGlzcGxheTogdGFibGU7DQogICAgICAgIGNsZWFyOiBib3RoOw0KICAgIH0NCiAgICAuY29tcG9uZW50LWNvbnRlbnQgew0KICAgICAgICB3aWR0aDogMTAwJTsNCiAgICAgICAgZmxvYXQ6IGxlZnQ7DQogICAgICAgIC5wcm9kdWN0LXZhcmlhbnQtbmFtZSB7DQogICAgICAgICAgICB3aWR0aDogNDglOw0KICAgICAgICAgICAgZmxvYXQ6IGxlZnQ7DQogICAgICAgICAgICBtYXJnaW4tcmlnaHQ6IDIlOw0KICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMTBweDsNCiAgICAgICAgfQ0KICAgICAgICAuaW52YWxpZC12YXJpYW50IHsNCiAgICAgICAgICAgIGNvbG9yOiAkc2Vjb25kYXJ5LXRleHQtY29sb3I7DQogICAgICAgIH0NCiAgICB9DQp9DQo=
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: scss
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 470
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/8D9302B030D044D794A0C0F9F906687B.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T100940Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2eaddd47-fb44-465f-a383-4cfc33195aef"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190424T025916Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
