---
ID: "fdf30654-42bf-43a4-a735-c5c95858fece"
Parent: "4f42c296-582c-4c0a-af87-e4439832dc90"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/sass/components/commerce/product-list-itemsonpage-component"
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: IEBpbXBvcnQgJy4uLy4uL2luZGV4JzsNCiAuY3hhLXByb2R1Y3RsaXN0aXRlbXNvbnBhZ2UtY29tcG9uZW50IHsNCiAgICBwYWRkaW5nLWxlZnQ6IDlweDsNCiAgICAgLnByb2R1Y3RsaXN0LWhlYWRlci1zZWN0aW9uIHsNCiAgICAgICAgIEBpbmNsdWRlIHJvdy1vZi1lbGVtZW50cy13aWRlLWFwYXJ0KGZhbHNlLCAkY2VudGVyKTsNCiAgICAgICAgIC5yZXN1bHRzLWNvbnRhaW5lciB7DQogICAgICAgICAgICAgQGluY2x1ZGUgcm93LW9mLWVsZW1lbnRzLXBhY2tlZChmYWxzZSwgJGNlbnRlciwgJHBhY2tlZC1lbGVtZW50cy1tYXJnaW4pOw0KICAgICAgICAgICAgIGxpbmUtaGVpZ2h0OiAyMnB4Ow0KICAgICAgICAgICAgIHNlbGVjdCB7DQogICAgICAgICAgICAgICAgIHdpZHRoOiAxMjBweDsNCiAgICAgICAgICAgICB9DQogICAgICAgICAgICAgc3BhbiB7DQogICAgICAgICAgICAgICAgY29sb3I6ICRzZWNvbmRhcnktdGV4dC1jb2xvcjsNCiAgICAgICAgICAgIH0NCiAgICAgICAgIH0NCiAgICAgfQ0KICAgICBtYXJnaW4tYm90dG9tOiAkbWFyZ2luKjI7DQogfQ0K
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: scss
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 552
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/85641115273D40E683FD2C2E4D8CFBCE.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T100939Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0080ff44-4db0-4375-a813-82177b1e4bb4"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20171120T100939Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
