---
ID: "820c91d1-90cd-4165-9bb6-1b3f81f0b912"
Parent: "10c8a0e3-9958-44ef-88ce-d0b38da9e72a"
Template: "e55834fb-7c93-44a2-87c0-62beba282ced"
Path: /sitecore/content/RobCommerce/RobStorefront/Home/Product catalog
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Software/32x32/branch.png
- ID: "2882072b-e310-406b-8dd9-b22c9ea4a0f3"
  Hint: CategoryDatasource
  Value: "/sitecore/content/RobCommerce/RobStorefront/Home/Catalogs/Habitat_Master/Habitat_Master-Departments"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171101T072226Z
