---
ID: "2b6f937f-59f8-4f07-9511-a3fc9aacb6b4"
Parent: "a246df15-efe6-4964-8bd7-153263161e9d"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/gulp/tasks/login
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/D011DDD19A944AF9B7D3ADF63CB4A921.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "ee05b087-a8b5-4d69-b9ff-c5fe180c42e7"
  Value: aW1wb3J0IGNvbmZpZyBmcm9tICcuLi9jb25maWcnOw0KaW1wb3J0IGlucXVpcmVyIGZyb20gJ2lucXVpcmVyJzsNCmltcG9ydCBndWxwIGZyb20gJ2d1bHAnOw0KDQpndWxwLnRhc2soJ2xvZ2luJywgZnVuY3Rpb24oKSB7DQogICAgdmFyIGxvZ2luUHJvbWlzZSA9IG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsNCiAgICAgICAgLy9pZiBhbHJlYWR5IGVudGVyZWQgY3JlZGVudGlhbHMNCiAgICAgICAgaWYgKGNvbmZpZy51c2VyLmxvZ2luLmxlbmd0aCkgew0KICAgICAgICAgICAgcmV0dXJuIHJlc29sdmUoY29uZmlnLnVzZXIpOw0KICAgICAgICB9DQogICAgICAgIGlucXVpcmVyLnByb21wdChjb25maWcubG9naW5RdWVzdGlvbnMpLnRoZW4oYW5zd2VyID0+IHsNCiAgICAgICAgICAgIGlmICghKGFuc3dlci5sb2dpbi5sZW5ndGggJiYgYW5zd2VyLnBhc3N3b3JkLmxlbmd0aCkpIHsNCiAgICAgICAgICAgICAgICByZWplY3QoJ2xvZ2luRXJyb3InKTsNCiAgICAgICAgICAgICAgICBwcm9jZXNzLmV4aXQoKTsNCiAgICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAgICAgcmVzb2x2ZShhbnN3ZXIpDQogICAgICAgICAgICAgICAgY29uZmlnLnVzZXIgPSBhbnN3ZXINCiAgICAgICAgICAgIH0NCiAgICAgICAgfSk7DQogICAgfSk7DQogICAgcmV0dXJuIGxvZ2luUHJvbWlzZTsNCn0p
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 687
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T065207Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
