---
ID: "13ed3d06-21dd-4188-9877-a6de01e0a22c"
Parent: "80a463f9-7296-4f37-a36f-dcb9ddb49b0e"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/gulp/tasks/sprites Copied from Storefront Branded Extension
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/70A2406BCACF4B858DEC10203984DF61.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "9637ca52-a103-4fab-8fa0-929d2a396115"
  Value: aW1wb3J0IGd1bHAgZnJvbSAiZ3VscCI7DQppbXBvcnQgc3ByaXRlc21pdGggZnJvbSAnZ3VscC5zcHJpdGVzbWl0aCc7DQppbXBvcnQgY29uZmlnIGZyb20gJy4uL2NvbmZpZyc7DQoNCmd1bHAudGFzaygnc3ByaXRlLWZsYWcnLCBmdW5jdGlvbigpIHsNCiAgICBsZXQgY29uZiA9IGNvbmZpZy5zcHJpdGVzLmZsYWdzLA0KICAgICAgICBzcHJpdGVEYXRhID0gZ3VscC5zcmMoY29uZi5mbGFnc0ZvbGRlcikucGlwZShzcHJpdGVzbWl0aChjb25mLnNwcml0ZXNtaXRoKSk7DQogICAgc3ByaXRlRGF0YS5pbWcucGlwZShndWxwLmRlc3QoY29uZi5pbWdEZXN0KSk7DQogICAgcmV0dXJuIHNwcml0ZURhdGEuY3NzLnBpcGUoZ3VscC5kZXN0KGNvbmYuY3NzRGVzdCkpOw0KfSk7
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 381
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180405T051927Z
