---
ID: "f62038bd-d519-4a6f-9fa5-27c46e903375"
Parent: "e5572b28-d687-4254-882b-1bd995628f24"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Commerce Experience Accelerator/Commerce Product Compare/Product Compare
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/document_notebook.png
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{FF75632A-03ED-4D31-B42A-1EEE45E5147F}"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/Experience Accelerator/Commerce/Catalog/Datasource/Product Compare
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "query:./ancestor::*[@@templatename='Site']/Data/Commerce/Catalog"
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductCompare
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: |
    Feature.Compare.Website.Controllers.ProductCompareController, Feature.Compare.Website
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Compare
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170215T093946Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
