---
ID: "48fa959c-e95d-407e-b7f3-4a2f9a062a7d"
Parent: "836e6f9c-e261-4ad1-ae4d-3d68e653ad78"
Template: "836e6f9c-e261-4ad1-ae4d-3d68e653ad78"
Path: "/sitecore/templates/Feature/Product Compare/Datasource/Add-View-Compare-Button/__Standard Values"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180823T013933Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "84ad6914-262e-42f6-aa6d-6f438bd5bd51"
      Hint: View Compare Text
      Value: View compare
    - ID: "ddf7a736-3405-411a-883b-c858802bea57"
      Hint: Add to Compare Text
      Value: Add to compare
