---
ID: "314ebe0c-1fd0-4caf-867c-d6e203d048dd"
Parent: "b46a1f1e-8201-4fbc-9c15-03fd82251401"
Template: "b46a1f1e-8201-4fbc-9c15-03fd82251401"
Path: /sitecore/templates/Project/RobCommerce/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190905T022338Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a5c83883-966b-4815-bb8d-f7be44a303dd"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190905T022338Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
