---
ID: "48fa959c-e95d-407e-b7f3-4a2f9a062a7d"
Parent: "836e6f9c-e261-4ad1-ae4d-3d68e653ad78"
Template: "836e6f9c-e261-4ad1-ae4d-3d68e653ad78"
Path: "/sitecore/templates/Feature/Product Compare/Datasource/Add-View-Compare-Button/__Standard Values"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "ddf7a736-3405-411a-883b-c858802bea57"
      Hint: Add to Compare Text
      Value: Add to compare
    - ID: "84ad6914-262e-42f6-aa6d-6f438bd5bd51"
      Hint: View Compare Text
      Value: View compare
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180823T013933Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7a4fa6ee-f535-4001-a5fd-89a8a9066a5c"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190903T070523Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
