---
ID: "b670bc78-5f83-401a-a13f-8678b7425869"
Parent: "bf2f4f81-93f0-42b9-83a3-878402714c31"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/RobCommerce/RobStorefront/Presentation/Rendering Variants/Image/Default
DB: master
BranchID: "cc5f46b4-6376-48b6-ad03-adc13508527f"
SharedFields:
- ID: "90294353-706a-431c-b855-cd245824d9fa"
  Hint: LinkField
  Value: File
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "file-type-icon-media-link"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D7856572-AFC2-4CB8-84A1-D4CAD015545D}"
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181215T073145Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181215T073201Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181215T072949Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181215T073217Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
