---
ID: "58e2de57-45b7-4f17-af3b-0cfea4de6d5f"
Parent: "2f8b3f8b-0bd1-443d-86e7-c5e28c24288b"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: "/sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/styles/components/commerce/product-image-component"
DB: master
SharedFields:
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "00000000-0000-0000-0000-000000000000"
  Value: LypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLypqdXN0aWZpY2F0aW9uIHR5cGVzKi8KLyogYWxpZ25tZW50IHR5cGVzICovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLUNvbHVtbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tUm93cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLyotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gRm9ybXMgYW5kIExheW91dCBUb29scy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSovCi8qLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFBhZ2UgTGF5b3V0cyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tKi8KLmN4YS1wcm9kdWN0aW1hZ2VzLWNvbXBvbmVudCB7CiAgbWFyZ2luOiAwOwp9CgouY3hhLXByb2R1Y3RpbWFnZXMtY29tcG9uZW50IC5wcm9kdWN0LWltYWdlIHsKICBwYWRkaW5nOiA1cHg7CiAgYmFja2dyb3VuZDogI2ZmZjsKICBib3JkZXItcmFkaXVzOiA0cHg7CiAgYm94LXNoYWRvdzogMCAxcHggNHB4IDAgcmdiYSgwLCAwLCAwLCAwLjEpOwp9CgouY3hhLXByb2R1Y3RpbWFnZXMtY29tcG9uZW50IC5wcm9kdWN0LWltYWdlIGltZyB7CiAgd2lkdGg6IDEwMCU7Cn0KCi5jeGEtcHJvZHVjdGltYWdlcy1jb21wb25lbnQgLnByb2R1Y3QtaW1hZ2VzIHsKICBiYWNrZ3JvdW5kOiBub25lOwogIG1hcmdpbi10b3A6IDE1cHg7Cn0KCi5jeGEtcHJvZHVjdGltYWdlcy1jb21wb25lbnQgLnByb2R1Y3QtaW1hZ2VzIHVsIGxpIHsKICBmbG9hdDogbGVmdDsKICBtYXJnaW4tcmlnaHQ6IDIuNiU7CiAgd2lkdGg6IDcycHg7CiAgaGVpZ2h0OiA2MnB4OwogIG1hcmdpbi1ib3R0b206IDEuOCU7CiAgb3ZlcmZsb3c6IGhpZGRlbjsKICBib3JkZXI6IDRweCBzb2xpZCAjZmZmOwp9CgouY3hhLXByb2R1Y3RpbWFnZXMtY29tcG9uZW50IC5wcm9kdWN0LWltYWdlcyB1bCBsaSBhIGltZyB7CiAgbWF4LXdpZHRoOiAxMjBweDsKICBtYXgtaGVpZ2h0OiAxMjBweDsKfQoKLmN4YS1wcm9kdWN0aW1hZ2VzLWNvbXBvbmVudCAucHJvZHVjdC1pbWFnZXMgdWwgbGkuYWN0aXZlOmJlZm9yZSB7CiAgYm9yZGVyLWxlZnQ6IDdweCBzb2xpZCB0cmFuc3BhcmVudDsKICBib3JkZXItcmlnaHQ6IDdweCBzb2xpZCB0cmFuc3BhcmVudDsKICBib3JkZXItYm90dG9tOiA4cHggc29saWQ7CiAgY29udGVudDogIiI7CiAgcG9zaXRpb246IGFic29sdXRlOwogIG1hcmdpbjogLTEwcHggMCAwIDI2cHg7Cn0KCi5jeGEtcHJvZHVjdGltYWdlcy1jb21wb25lbnQgLnByb2R1Y3QtaW1hZ2VzIHVsIGxpLmFjdGl2ZSB7CiAgYm9yZGVyOiA0cHggc29saWQgIzBlOTA5ZjsKICAtd2Via2l0LXRyYW5zaXRpb246IGJvcmRlciAwLjJzOwogIHRyYW5zaXRpb246IGJvcmRlciAwLjJzOwp9CgouY3hhLXByb2R1Y3RpbWFnZXMtY29tcG9uZW50IC5wcm9kdWN0LWltYWdlcyB1bCBsaS5hY3RpdmU6YmVmb3JlIHsKICBib3JkZXItYm90dG9tLWNvbG9yOiAjMGU5MDlmOwp9Cg==
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: css
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: text/css
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2560
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/D43A6D088A964E7F9ED2FB7662E15D6F.ashx?h=16&thn=1&w=16"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171120T095743Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "236359c3-f897-4f16-bd52-3bfab3720328"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20180222T082632Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
