---
ID: "2f4e029e-6dcf-4eca-addb-e82c698e4823"
Parent: "2bb9b222-b024-4f04-812a-6ceedba3a59c"
Template: "2bb9b222-b024-4f04-812a-6ceedba3a59c"
Path: /sitecore/templates/Project/RobCommerce/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181215T072628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
