---
ID: "8d49f0e9-5426-4ed5-85b5-bcaf3c12e46b"
Parent: "5ecca55a-4fa9-4510-8897-c51e528bc3f2"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/RobCommerce/RobStorefront/RobStorefront/sass/base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T063530Z
